import { useEffect, useId, useRef, useState } from 'react';

/**
 * The Uncloud wordmark: lowercase, with the O replaced by the cloud mark
 * carrying the brand's amber gradient.
 *
 * The cloud is the app icon too, so the two marks are literally the same
 * drawing.
 *
 * Its geometry is MEASURED, not eyeballed. The supplied artwork was traced
 * first, which inherited the source's 141-pixel noise and came out lumpy — the
 * mark is plainly geometric, so the shape was refitted instead: a cap circle,
 * two shoulders, and a body whose bottom corners round separately. Six
 * parameters, hill-climbed against the artwork's own silhouette, agreeing with
 * it to within 0.84% of its area. Everything below is in a 100-wide box, which
 * is why the numbers have two decimal places rather than being round.
 */

interface Cloud {
  /** Width of this cloud's box; the height follows from `h`. */
  w: number;
  h: number;
  /** The cap: one circle, centred. */
  r1: number;
  cy1: number;
  /** The shoulders, tangent to each side. */
  rl: number;
  yl: number;
  /** The body's bottom corners, which round independently of the shoulders. */
  rb: number;
  /** Where the body starts, under the cap. */
  top: number;
}

const OUTER: Cloud = {
  w: 100, h: 72.34,
  r1: 29.08, cy1: 28.37, rl: 26.24, yl: 46.10, rb: 26.24, top: 40.43,
};

/** The cloud cut out of the middle. Not a scaled copy of the outer one — the
 *  artwork's inner cloud is squatter, and copying the outer proportions here
 *  made it read as a keyhole rather than a cloud. */
const INNER: Cloud = {
  w: 58.87, h: 34.04,
  r1: 15.60, cy1: 15.60, rl: 9.93, yl: 24.11, rb: 9.93, top: 22.70,
};
const INNER_AT = { x: 20.57, y: 21.28 };

/** One cloud, as the shapes it is made of.
 *
 *  Drawn as overlapping primitives rather than a single path because that is
 *  what it is, and a path would have to be regenerated by hand every time a
 *  proportion changed. The gradient is in user space so the overlaps are
 *  seamless — per-object bounding boxes would restart the sweep on every
 *  circle and show every seam.
 */
function shapes(c: Cloud, ox = 0, oy = 0) {
  const cx = ox + c.w / 2;
  return (
    <>
      <circle cx={cx} cy={oy + c.cy1} r={c.r1} />
      <circle cx={ox + c.rl} cy={oy + c.yl} r={c.rl} />
      <circle cx={ox + c.w - c.rl} cy={oy + c.yl} r={c.rl} />
      <circle cx={ox + c.rb} cy={oy + c.h - c.rb} r={c.rb} />
      <circle cx={ox + c.w - c.rb} cy={oy + c.h - c.rb} r={c.rb} />
      <rect x={ox + c.rb} y={oy + c.top} width={c.w - 2 * c.rb} height={c.h - c.top} />
      <rect x={ox} y={oy + c.yl} width={c.w} height={c.h - c.rb - c.yl} />
    </>
  );
}

/** The mark on its own. `px` is its WIDTH; a cloud is wider than it is tall. */
export function Mark({ px, spinning = false }: { px: number; spinning?: boolean }) {
  // Unique per instance: several marks can be on screen at once and duplicate
  // gradient ids would make them all resolve to whichever mounted first.
  const gid = useId();
  return (
    <svg viewBox={`0 0 ${OUTER.w} ${OUTER.h}`} width={px}
         height={px * OUTER.h / OUTER.w} aria-hidden="true"
         style={{ display: 'block', flex: 'none' }}>
      <defs>
        {/* Top to bottom, following the artwork. The cog this replaced swept
            diagonally, which on a cloud read as a lighting error. */}
        <linearGradient id={gid} gradientUnits="userSpaceOnUse"
                        x1="0" y1="0" x2="0" y2={OUTER.h}>
          <stop offset="0%" stopColor="var(--accent, #f59e0b)" />
          <stop offset="100%" stopColor="var(--accent-2, #dc2626)" />
        </linearGradient>
      </defs>
      {/* A cloud does not spin. Where the cog rotated to say "working", this
          breathes — the same signal without implying machinery. */}
      <g style={spinning
        ? { animation: 'uncloud-drift 2.6s ease-in-out infinite',
            transformOrigin: '50% 60%' }
        : undefined}>
        <g fill={`url(#${gid})`}>{shapes(OUTER)}</g>
        {/* The knockout. It is the ground colour rather than transparent so the
            mark can sit on a card, a gradient or a photograph unchanged —
            which is exactly what the supplied icon tiles do. */}
        <g fill="var(--bg, #0a0a0c)">{shapes(INNER, INNER_AT.x, INNER_AT.y)}</g>
      </g>
    </svg>
  );
}

/**
 * Loading state: the word assembles itself. Characters land left to right while
 * the whole mark stays centred, so it grows outward from the middle, and the
 * extra tracking on an unsettled glyph collapses to normal as it arrives.
 *
 * Laid out in a frame loop rather than CSS keyframes because the centred growth
 * needs real widths — a glyph that has not landed yet must occupy no space, and
 * CSS cannot interpolate to a text run's intrinsic width.
 */
const GLYPHS = ['u', 'n', 'c', 'l', null, 'u', 'd'] as const;  // null is the cloud
const STAGGER = 0.085;
const EXTRA = 0.52;      // additional tracking while a glyph settles, in em
const CYCLE = 2600;      // ms for one full assemble, hold and reset

function smooth(t: number) {
  const x = Math.max(0, Math.min(1, t));
  return x * x * (3 - 2 * x);
}

export default function Wordmark({
  size = 28,
  spinning = false,
  className = '',
}: {
  size?: number;
  spinning?: boolean;
  className?: string;
}) {
  // Measured off the artwork: the cloud stands 1.15x the x-height, and is
  // 1.382x its own height wide. Expressed against the font size through
  // Montserrat's x-height so it holds at every size.
  const markWidth = size * X_HEIGHT * MARK_TO_X_HEIGHT * (OUTER.w / OUTER.h);
  const refs = useRef<(HTMLSpanElement | null)[]>([]);
  const [widths, setWidths] = useState<number[] | null>(null);
  const [p, setP] = useState(1);

  // Measure once at rest; the animation needs each glyph's natural width.
  useEffect(() => {
    const w = refs.current.map((el, i) =>
      i === 4 ? markWidth : (el?.getBoundingClientRect().width ?? 0),
    );
    if (w.every((n) => n > 0)) setWidths(w);
  }, [size, markWidth]);

  useEffect(() => {
    if (!spinning || !widths) { setP(1); return; }
    if (window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) return;
    let raf = 0;
    const t0 = performance.now();
    const tick = (now: number) => {
      const phase = ((now - t0) % CYCLE) / CYCLE;
      // Assemble over the first 70%, hold, then reset for the next pass.
      setP(phase < 0.7 ? phase / 0.7 : 1);
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [spinning, widths]);

  const n = GLYPHS.length;
  const win = 1 - STAGGER * (n - 1);
  const gp = GLYPHS.map((_, i) =>
    widths && spinning ? smooth((p - STAGGER * i) / win) : 1,
  );

  return (
    <span
      //: The gradient is clipped to the text of the WORD, not of each letter.
      //  Per-glyph it would repeat the whole amber-to-rose sweep six times over
      //  and read as noise; across the word it reads as one mark, and matches
      //  the cog sitting in the middle of it. The cog is an SVG with its own
      //  fill, so text-fill-color leaves it alone.
      className={`inline-flex items-baseline select-none grad-text ${className}`}
      style={{ fontSize: size, lineHeight: 1 }}
      role="img"
      aria-label="Uncloud"
    >
      {GLYPHS.map((ch, i) => {
        const natural = widths ? widths[i] : undefined;
        const advance =
          natural === undefined
            ? undefined
            : (natural + EXTRA * size * (1 - gp[i])) * gp[i];
        return (
          <span
            key={i}
            ref={(el) => { refs.current[i] = el; }}
            style={{
              display: 'inline-flex',
              justifyContent: 'center',
              overflow: 'visible',
              // The mark has no baseline of its own, so it is dropped onto the
              // letters' one. Without this it floats, because a flex row
              // aligns an SVG box by its edge and a glyph by its baseline.
              ...(ch === null ? { alignSelf: 'baseline',
                                  transform: `translateY(${size * 0.02}px)` }
                              : {}),
              opacity: gp[i],
              width: advance,
              ...(ch === null ? {} : letter),
            }}
          >
            {ch === null ? <Mark px={markWidth} /> : ch}
          </span>
        );
      })}
    </span>
  );
}

/** Montserrat's x-height, as a share of the em. The mark is sized against the
 *  letters rather than against the font size, so it keeps its relationship to
 *  them at every size. */
const X_HEIGHT = 0.517;

/** How much taller than the x-height the cloud stands. From the artwork:
 *  105 against 98. */
const MARK_TO_X_HEIGHT = 1.15;

const letter: React.CSSProperties = {
  fontFamily: "var(--display, 'Montserrat', system-ui, sans-serif)",
  // 700, not 900, and the tracking is nearly normal. Both are measured: the
  // artwork's 'l' is 30 units wide against a 151-unit ascender, a stem-to-
  // height ratio of 0.199 — Montserrat Bold to two decimal places, where Black
  // is 0.29. At 900 with -0.07em the lowercase word came out as a dense block
  // and stopped looking like the mark it is meant to be.
  fontWeight: 700,
  letterSpacing: '-0.01em',
};
