"""The shared Uncloud foundation.

BYTE-IDENTICAL IN BOTH REPOSITORIES — see `capability.py` for why, and for the
rules anything added here has to obey. A test in each product compares the
copies and fails when they drift.

Shared by copying rather than by packaging, deliberately and for now. Both
applications ship their engine as source and build it on the customer's machine
with `uv`, so a real dependency would have to be published and credentialed
into both builds. That is the right answer once this layer is large; while it
is two files it would be more machinery than the problem.
"""

from .capability import (
    RUNTIMES,
    UNKNOWN_RUNTIME,
    VOCABULARY_VERSION,
    Capability,
    CommercialUse,
    Component,
    Cost,
    Licence,
    Modality,
    ModelProfile,
    ReasoningSupport,
    RuntimeProfile,
    fits,
    reasoning_support,
    runtime_profile,
    with_capability,
)
from .effort import (
    BASE_OUTPUT_TOKENS,
    BLURBS,
    BUDGETS,
    LABELS,
    ORDER,
    Budget,
    Effort,
    Plan,
    describe,
    parse,
    translate,
)
from .evaluation import (
    ADHERENCE,
    COMPOSITION,
    CONSISTENCY,
    DEFECTS,
    EVALUATION_VERSION,
    NOT_BLANK,
    Dimension,
    Evaluator,
    Judge,
    Regression,
    Result,
    Rubric,
    Score,
    Unmeasurable,
    best,
    compare,
    evaluate,
)
from .permission import (
    ALWAYS_ASK,
    DEFAULTS,
    POLICY_VERSION,
    ApprovalRequired,
    AuditEntry,
    AuditLog,
    Decision,
    Denied,
    Gate,
    Mode,
    Request,
    Risk,
    clamp,
    dump_policy,
    load_policy,
)

__all__ = [
    "ADHERENCE",
    "ALWAYS_ASK",
    "BASE_OUTPUT_TOKENS",
    "BLURBS",
    "BUDGETS",
    "COMPOSITION",
    "CONSISTENCY",
    "DEFAULTS",
    "DEFECTS",
    "EVALUATION_VERSION",
    "LABELS",
    "NOT_BLANK",
    "ORDER",
    "POLICY_VERSION",
    "RUNTIMES",
    "UNKNOWN_RUNTIME",
    "VOCABULARY_VERSION",
    "ApprovalRequired",
    "AuditEntry",
    "AuditLog",
    "Budget",
    "Capability",
    "CommercialUse",
    "Component",
    "Cost",
    "Decision",
    "Dimension",
    "Denied",
    "Effort",
    "Evaluator",
    "Gate",
    "Judge",
    "Licence",
    "Modality",
    "Mode",
    "ModelProfile",
    "Plan",
    "ReasoningSupport",
    "Regression",
    "Request",
    "Result",
    "Risk",
    "Rubric",
    "RuntimeProfile",
    "Score",
    "Unmeasurable",
    "best",
    "clamp",
    "compare",
    "describe",
    "dump_policy",
    "evaluate",
    "fits",
    "load_policy",
    "parse",
    "reasoning_support",
    "runtime_profile",
    "translate",
    "with_capability",
]
